application: websitegautam #My GAE project id
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: .*  # Direct all routes to FlaskServer.py
  script: FlaskServer.app

# libraries:
# - name: webapp2
#   version: "2.5.2"