application: websitegautam #My GAE project id
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /images
  static_dir: images

- url: .*  # Direct all routes to FlaskServer.py
  script: FlaskServer.app